dataset: Market-1501-v15.09.15  # dataset path
weights: results/aligned.pth  # model weights
aligned: true  # use local distance loss
epochs: 60
batch: 384  # higher batch sizes yield better results
scaler: true  # automatic mixed precision training
step: 6  # StepLR steps
gamma: 0.5  # StepLR gamma
global_margin: 0.5  # triplet loss margin for global feature
local_margin: 0.25  # triplet loss margin for local feature
workers: 2
persistent: true
optimizer: SGD  # SGD | AdamW
sgd:
  lr: 0.05
  momentum: 0.9
  decay: !!float 0  # weight decay
  nesterov: true
adamw:
  lr: 0.001
  betas:
    - 0.9  # beta 1
    - 0.99  # beta 2
  decay: 0.01  # weight decay
topk: 5  # top-k for top-k re-ranking, n_neighbors for KNN
knn: true  # use KNN for re-ranking
kmeans: true  # use kmeans disntace metric for cluster re-ranking